#define VERSION	     "2.0.9"
#define LONG_VERSION "2.0.9 (21 September 2000)"
#define COPYLEFT     "(c) 1996-2000, Nicolas Hadacek"
#define EMAIL        "hadacek@kde.org"
#define HOMEPAGE     "http://azhyd.free.fr/KDE/kmines.php3"
