#define VERSION	     "2.1.9a"
#define LONG_VERSION "2.1.9a (25 Aug 2005)"
#define COPYLEFT     "(c) 1996-2005, Nicolas Hadacek\n(c) 2001, Mikhail Kourinny"
#define EMAIL        "hadacek@kde.org"
#define HOMEPAGE     "http://kmines.sourceforge.net/"
